version: '3.7'
services:

  fullfront:
    build: .
    restart: on-failure
    ports:
    - 8080:8080
    networks:
      - fullfront-network

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    networks:
      - fullfront-network
#    volumes:
#      - ./mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - fullfront-network

networks:
  fullfront-network:
    driver: bridge
