version: '3.7'
services:

  backend:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - some-net

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - /data/db:/data/db
    networks:
      - some-net

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - some-net

networks:
  some-net:
    driver: bridge
